import type { BusinessProfilePlaybook } from "@novussync/domain";

export const YOGA_STUDIO_PLAYBOOK_V1 = {
  id: "independent-yoga-studio-en-in",
  version: 1,
  businessType: "Independent yoga studio",
  locale: "en-IN",
  fields: [
    {
      key: "business_name",
      section: "business",
      label: "Business name",
      description: "The public studio or business name customers should see.",
      kind: "short_text",
      required: true,
      maxLength: 120,
    },
    {
      key: "business_summary",
      section: "business",
      label: "Business summary",
      description: "A factual description of the studio, services, and operating model.",
      kind: "long_text",
      required: true,
      maxLength: 1200,
    },
    {
      key: "primary_location",
      section: "business",
      label: "Primary location",
      description: "The customer-facing neighbourhood, city, and country.",
      kind: "short_text",
      required: true,
      maxLength: 200,
    },
    {
      key: "introductory_offer",
      section: "offer",
      label: "Introductory offer",
      description: "The exact trial or introductory experience currently offered.",
      kind: "long_text",
      required: true,
      maxLength: 800,
    },
    {
      key: "offer_price",
      section: "offer",
      label: "Offer price",
      description: "The owner-confirmed price and currency, or a clear statement that it is free.",
      kind: "short_text",
      required: true,
      maxLength: 120,
    },
    {
      key: "ideal_audience",
      section: "audience",
      label: "Ideal audience",
      description: "The people this introductory offer is designed to serve.",
      kind: "long_text",
      required: true,
      maxLength: 900,
    },
    {
      key: "audience_exclusions",
      section: "audience",
      label: "Audience exclusions",
      description: "People or needs that require another service, professional, or human review.",
      kind: "list",
      required: false,
      maxItems: 12,
      itemMaxLength: 240,
    },
    {
      key: "brand_voice",
      section: "voice",
      label: "Brand voice",
      description: "How customer-facing language should sound and what tone should be avoided.",
      kind: "long_text",
      required: true,
      maxLength: 800,
    },
    {
      key: "frequently_asked_questions",
      section: "faqs",
      label: "Frequently asked questions",
      description: "Owner-approved question and answer pairs, one pair per item.",
      kind: "list",
      required: true,
      maxItems: 20,
      itemMaxLength: 600,
    },
    {
      key: "claims_boundary",
      section: "claims",
      label: "Claims boundary",
      description: "Claims the business can support and health or outcome claims it must not make.",
      kind: "long_text",
      required: true,
      maxLength: 1200,
    },
    {
      key: "customer_restrictions",
      section: "restrictions",
      label: "Customer restrictions",
      description: "Injury, age, pregnancy, therapy, or suitability cases requiring owner review.",
      kind: "list",
      required: true,
      maxItems: 20,
      itemMaxLength: 320,
    },
    {
      key: "approval_requirements",
      section: "restrictions",
      label: "Approval requirements",
      description:
        "Pricing, schedule, discount, health, or commitment decisions reserved for an owner.",
      kind: "list",
      required: true,
      maxItems: 20,
      itemMaxLength: 320,
    },
    {
      key: "booking_route_label",
      section: "booking",
      label: "Booking route label",
      description: "The owner-approved name of the external or operator-assisted booking route.",
      kind: "short_text",
      required: true,
      maxLength: 160,
    },
    {
      key: "booking_route_url",
      section: "booking",
      label: "Booking route URL",
      description: "An HTTPS link to the approved provider-managed booking route, when available.",
      kind: "url",
      required: false,
      maxLength: 1000,
    },
    {
      key: "attendance_confirmation",
      section: "booking",
      label: "Attendance confirmation",
      description: "How a named human or approved provider record confirms the customer outcome.",
      kind: "long_text",
      required: true,
      maxLength: 800,
    },
  ],
} as const satisfies BusinessProfilePlaybook;
